# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20171019_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160),
        ),
    ]
